# Generated by Django 4.2 on 2023-04-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='Exam_duration',
        ),
    ]
