# Generated by Django 4.2 on 2023-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
