# Generated by Django 4.2 on 2023-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
